name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure IntelliJ IDEA
        run: |
          setx PATH "%PATH%;C:\Program Files\JetBrains\IntelliJ IDEA\bin"

      - name: Set up Maven
        run: |
          curl -L -o apache-maven.zip https://apache.osuosl.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
          Expand-Archive -Path apache-maven.zip -DestinationPath . -Force
          if ($?) {
            Write-Host "Maven setup successful"
            $env:PATH += ";$(pwd)/apache-maven-3.8.4/bin"
          } else {
            Write-Host "Failed to set up Maven"
            exit 1
          }

      - name: Build application
        run: mvn compile

      - name: Test
        run: mvn test

  deploy:
    name: Deploy to Production
    needs: [build]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # Add commands to deploy your application to production servers here
