name: pipeline CI/CD

on:
  push:
    branches:
      - main  # adjust this to your main branch name
  pull_request:
    branches:
      - main  # adjust this to your main branch name

jobs:
  build:
    runs-on: windows-latest  # using Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # adjust this to your Java version
        distribution: 'adopt'
        javaHome: 'C:\\jdk-21'  # path to your JDK installation

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # adjust this to your Java version
        distribution: 'adopt'
        server-id: repo
        settings-path: ${{ github.workspace }}  # assuming Maven settings.xml is in the project root

    - name: Build with Maven
      run: mvn -B package --file pom.xml  # adjust the Maven command as per your project setup

  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # adjust this to your Java version
        distribution: 'adopt'
        javaHome: 'C:\\jdk-21'  # path to your JDK installation

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '21'  # adjust this to your Java version
        distribution: 'adopt'
        server-id: repo
        settings-path: ${{ github.workspace }}  # assuming Maven settings.xml is in the project root

    - name: Run tests with Maven
      run: mvn test  # adjust the Maven command as per your project setup
